#! /bin/sh

# autostart
sxhkd &
xsetroot -cursor_name left_ptr &
lxpolkit &
xfce4-power-manager &
pipewire &
pipewire-pulse &
picom &
killall polybar
polybar bspwm &
#$HOME/.config/polybar/launch.sh
nitrogen --restore &

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config focus_by_distance     true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#444444"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#427b58"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lutris  state=floating
bspc rule -a battle.net.exe desktop='^1' state=floating
bspc rule -a discord desktop='^2' state=floating
bspc rule -a wow.exe desktop='^3'
bspc rule -a wowclassic.exe desktop='^3'
bspc rule -a Galculator state=floating
bspc rule -a XClock state=floating
