alias v="nvim"
alias kde="dbus-run-session startplasma-wayland"
alias sway="dbus-run-session sway"
#alias sway="dbus-run-session sway --unsupported-gpu -D noscanout"
alias reboot="loginctl reboot"
alias shutdown="loginctl poweroff"
