#!/bin/bash
sxhkd -c $HOME/.config/berry/sxhkdrc &
xsetroot -cursor_name left_ptr &
lxpolkit &
picom  &
pipewire &
pipewire-pulse &
killall polybar
polybar -c ~/.config/polybar/config.ini hlwm &
nitrogen --restore &

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       20
berryc top_gap            25

# Set decoration colors
berryc focus_color         282828
berryc unfocus_color       282828
berryc inner_focus_color   d65d0e
berryc inner_unfocus_color 458588
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "DejaVu-9"
berryc focus_follows_pointer "false"
